logging:
  level:
    org.springframework.web: INFO
    org.flowable.engine: DEBUG

server:
  port: 8080

spring:
  application:
    name: microsrv-flowable
  aop:
    auto: true
    proxy-target-class: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      resolve-lazily: false
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    initialization-mode: never
    url: jdbc:mysql://172.23.216.48:3306/flowable?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: "!QAZ2wsx3edc"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 30000
      connection-timeout: 30000
      minimum-idle: 2
      maximum-pool-size: 5
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

flowable:
  database-schema-update: true
  #using a message queue a component that manages a thread pool to fire timers and other asynchronous tasks
  async-executor-activate: false
  process:
    definition-cache-limit: 10

# ===================================================================
# Common Flowable Spring Boot Properties
#
# This sample file is provided as a guideline. Do NOT copy it in its
# entirety to your own application.	           ^^^
# ===================================================================

# Core (Process) FlowableProperties
#  flowable.check-process-definitions=true # Whether process definitions need to be auto deployed.
#  flowable.custom-mybatis-mappers= # The FQN of custom Mybatis mappers that need to be added to the engine.
#  flowable.custom-mybatis-x-m-l-mappers= # The location of the custom Mybatis XML Mappers that need to be added to the engine.
#  flowable.database-schema= # In some situations you want to set the schema to use for table checks / generation if the database metadata doesn't return that correctly.
#  flowable.database-schema-update=true # The strategy that should be used for the database schema.
#  flowable.db-history-used=true # Whether db history should be used.
#  flowable.deployment-name=SpringBootAutoDeployment # The name of the auto deployment.
#  flowable.history-level= # The history level that needs to be used.
#  flowable.process-definition-location-prefix=classpath*:/processes/ # The folder in which processes need to be searched for auto deployment.
#  flowable.process-definition-location-suffixes=**.bpmn20.xml,**.bpmn # The suffixes (extensions) of the files that needs to be deployed from the 'processDefinitionLocationPrefix' location.
#
#  # Process FlowableProcessProperties
#  flowable.process.definition-cache-limit=-1 # The maximum amount of process definitions available in the process definition cache. Per default it is 1 (all process definitions).
#  flowable.process.enable-safe-xml=true # Enables extra checks on the BPMN xml that is parsed. See https://www.flowable.org/docs/userguide/index.html#advanced.safe.bpmn.xml. Unfortunately, this feature is not available on some platforms (JDK 6, JBoss), hence you need to disable if your platform does not allow the use of StaxSource during XML parsing.
#  flowable.process.servlet.load-on-startup=-1 # Load on startup of the Process dispatcher servlet.
#  flowable.process.servlet.name=Flowable BPMN Rest API # The name of the Process servlet.
#  flowable.process.servlet.path=/process-api # The context path for the Process rest servlet.
#
#  # Process Async Executor
#  flowable.process.async-executor-activate=true # Whether the async executor should be activated.
#  flowable.process.async.executor.async-job-lock-time-in-millis=300000 # The amount of time (in milliseconds) an async job is locked when acquired by the async executor. During this period of time, no other async executor will try to acquire and lock this job.
#  flowable.process.async.executor.default-async-job-acquire-wait-time-in-millis=10000 # The time (in milliseconds) the async job acquisition thread will wait to execute the next acquirement query. This happens when no new async jobs were found or when less async jobs have been fetched. Default value = 10 seconds.
#  flowable.process.async.executor.default-queue-size-full-wait-time-in-millis=0 # The time (in milliseconds) the async job (both timer and async continuations) acquisition thread will wait when the queue is full to execute the next query. By default set to 0 (for backwards compatibility)
#  flowable.process.async.executor.default-timer-job-acquire-wait-time-in-millis=1000 # The time (in milliseconds) the timer job acquisition thread will wait to execute the next acquirement query. This happens when no new timer jobs were found or when less async jobs have been fetched. Default value = 10 seconds.
#  flowable.process.async.executor.max-async-jobs-due-per-acquisition=1 # ???
#  flowable.process.async.executor.retry-wait-time-in-millis=500 # ???
#  flowable.process.async.executor.timer-lock-time-in-millis=300000 # The amount of time (in milliseconds) a timer job is locked when acquired by the async executor. During this period of time, no other async executor will try to acquire and lock this job.
#
#
#  # CMMN FlowableCmmnProperties
#  flowable.cmmn.deploy-resources=true # Whether to perform deployment of resources, default is 'true'.
#  flowable.cmmn.deployment-name=SpringBootAutoDeployment # The name of the deployment for the CMMN resources.
#  flowable.cmmn.enable-safe-xml=true # Enables extra checks on the DMN xml that is parsed. See https://www.flowable.org/docs/userguide/index.html#advanced.safe.bpmn.xml. Unfortunately, this feature is not available on some platforms (JDK 6, JBoss), hence you need to disable if your platform does not allow the use of StaxSource during XML parsing.
#  flowable.cmmn.enabled=true # Whether the CMMN engine needs to be started.
#  flowable.cmmn.resource-location=classpath*:/cases/ # The location where the CMMN resources are located.
#  flowable.cmmn.resource-suffixes=**.cmmn,**.cmmn11,**.cmmn.xml,**.cmmn11.xml # The suffixes for the resources that need to be scanned.
#  flowable.cmmn.servlet.load-on-startup=-1 # Load on startup of the CMMN dispatcher servlet.
#  flowable.cmmn.servlet.name=Flowable CMMN Rest API # The name of the CMMN servlet.
#  flowable.cmmn.servlet.path=/cmmn-api # The context path for the CMMN rest servlet.
#
#  # CMMN Async Executor
#  flowable.cmmn.async-executor-activate=true # Whether the async executor should be activated.
#  flowable.cmmn.async.executor.async-job-lock-time-in-millis=300000 # The amount of time (in milliseconds) an async job is locked when acquired by the async executor. During this period of time, no other async executor will try to acquire and lock this job.
#  flowable.cmmn.async.executor.default-async-job-acquire-wait-time-in-millis=10000 # The time (in milliseconds) the async job acquisition thread will wait to execute the next acquirement query. This happens when no new async jobs were found or when less async jobs have been fetched. Default value = 10 seconds.
#  flowable.cmmn.async.executor.default-queue-size-full-wait-time-in-millis=0 # The time (in milliseconds) the async job (both timer and async continuations) acquisition thread will wait when the queue is full to execute the next query. By default set to 0 (for backwards compatibility)
#  flowable.cmmn.async.executor.default-timer-job-acquire-wait-time-in-millis=1000 # The time (in milliseconds) the timer job acquisition thread will wait to execute the next acquirement query. This happens when no new timer jobs were found or when less async jobs have been fetched. Default value = 10 seconds.
#  flowable.cmmn.async.executor.max-async-jobs-due-per-acquisition=1 # ???
#  flowable.cmmn.async.executor.retry-wait-time-in-millis=500 # ???
#  flowable.cmmn.async.executor.timer-lock-time-in-millis=300000 # The amount of time (in milliseconds) a timer job is locked when acquired by the async executor. During this period of time, no other async executor will try to acquire and lock this job.
#
#  # Content FlowableContentProperties
#  flowable.content.enabled=true # Whether the content engine needs to be started.
#  flowable.content.servlet.load-on-startup=-1 # Load on startup of the Content dispatcher servlet.
#  flowable.content.servlet.name=Flowable Content Rest API # The name of the Content servlet.
#  flowable.content.servlet.path=/content-api # The context path for the Content rest servlet.
#  flowable.content.storage.create-root=true # If the root folder doesn't exist, should it be created?
#  flowable.content.storage.root-folder= # Root folder location where content files will be stored, for example, task attachments or form file uploads.
#
#  # DMN FlowableDmnProperties
#  flowable.dmn.deploy-resources=true # Whether to perform deployment of resources, default is 'true'.
#  flowable.dmn.deployment-name=SpringBootAutoDeployment # The name of the deployment for the dmn resources.
#  flowable.dmn.enable-safe-xml=true # Enables extra checks on the DMN xml that is parsed. See https://www.flowable.org/docs/userguide/index.html#advanced.safe.bpmn.xml. Unfortunately, this feature is not available on some platforms (JDK 6, JBoss), hence you need to disable if your platform does not allow the use of StaxSource during XML parsing.
#  flowable.dmn.enabled=true # Whether the dmn engine needs to be started.
#  flowable.dmn.history-enabled=true # Whether the history for the DMN engine should be enabled.
#  flowable.dmn.resource-location=classpath*:/dmn/ # The location where the dmn resources are located.
#  flowable.dmn.resource-suffixes=**.dmn,**.dmn.xml,**.dmn11,**.dmn11.xml # The suffixes for the resources that need to be scanned.
#  flowable.dmn.servlet.load-on-startup=-1 # Load on startup of the DMN dispatcher servlet.
#  flowable.dmn.servlet.name=Flowable DMN Rest API # The name of the DMN servlet.
#  flowable.dmn.servlet.path=/dmn-api # The context path for the DMN rest servlet.
#  flowable.dmn.strict-mode=true # Set this to false if you want to ignore the decision table hit policy validity checks to result in an failed decision table state. A result is that intermediate results created up to the point the validation error occurs are returned.
#
#  # Form FlowableFormProperties
#  flowable.form.deploy-resources=true # Whether to perform deployment of resources, default is true.
#  flowable.form.deployment-name=SpringBootAutoDeployment # The name of the deployment for the form resources.
#  flowable.form.enabled=true # Whether the form engine needs to be started.
#  flowable.form.resource-location=classpath*:/forms/ # The location where the form resources are located.
#  flowable.form.resource-suffixes=**.form # The suffixes for the resources that need to be scanned.
#  flowable.form.servlet.load-on-startup=-1 # Load on startup of the Form dispatcher servlet.
#  flowable.form.servlet.name=Flowable Form Rest API # The name of the Form servlet.
#  flowable.form.servlet.path=/form-api # The context path for the Form rest servlet.
#
#  # IDM FlowableIdmProperties
#  flowable.idm.enabled=true # Whether the idm engine needs to be started.
#  flowable.idm.password-encoder= # The type of the password encoder that needs to be used.
#  flowable.idm.servlet.load-on-startup=-1 # Load on startup of the IDM dispatcher servlet.
#  flowable.idm.servlet.name=Flowable IDM Rest API # The name of the IDM servlet.
#  flowable.idm.servlet.path=/idm-api # The context path for the IDM rest servlet.
#
#  # IDM Ldap FlowableLdapProperties
#  flowable.idm.ldap.attribute.email= # Name of the attribute that matches the user email.
#  flowable.idm.ldap.attribute.first-name= # Name of the attribute that matches the user first name.
#  flowable.idm.ldap.attribute.group-id= # Name of the attribute that matches the group id.
#  flowable.idm.ldap.attribute.group-name= # Name of the attribute that matches the group name.
#  flowable.idm.ldap.attribute.group-type= # Name of the attribute that matches the group type.
#  flowable.idm.ldap.attribute.last-name= # Name of the attribute that matches the user last name.
#  flowable.idm.ldap.attribute.user-id= # Name of the attribute that matches the user id.
#  flowable.idm.ldap.base-dn= # The base 'distinguished name' (DN) from which the searches for users and groups are started.
#  flowable.idm.ldap.cache.group-size=-1 # Allows to set the size of the {@link org.flowable.ldap.LDAPGroupCache}. This is an LRU cache that caches groups for users and thus avoids hitting the LDAP system each time the groups of a user needs to be known.
#  flowable.idm.ldap.custom-connection-parameters= # Allows to set all LDAP connection parameters which do not have a dedicated setter. See for example http://docs.oracle.com/javase/tutorial/jndi/ldap/jndi.html for custom properties. Such properties are for example to configure connection pooling, specific security settings, etc.
#  flowable.idm.ldap.enabled=false # Whether to enable LDAP IDM Service.
#  flowable.idm.ldap.group-base-dn= # The base 'distinguished name' (DN) from which the searches for groups are started.
#  flowable.idm.ldap.initial-context-factory=com.sun.jndi.ldap.LdapCtxFactory # The class name for the initial context factory.
#  flowable.idm.ldap.password= # The password that is used to connect to the LDAP system.
#  flowable.idm.ldap.port=-1 # The port on which the LDAP system is running.
#  flowable.idm.ldap.query.all-groups= # The query that is executed when searching for all groups.
#  flowable.idm.ldap.query.all-users= # The query that is executed when searching for all users.
#  flowable.idm.ldap.query.groups-for-user= # The query that is executed when searching for the groups of a specific user.
#  flowable.idm.ldap.query.user-by-full-name-like= # The query that is executed when searching for a user by full name.
#  flowable.idm.ldap.query.user-by-id= # The query that is executed when searching for a user by userId.
#  flowable.idm.ldap.search-time-limit=0 # The timeout (in milliseconds) that is used when doing a search in LDAP. By default set to '0', which means 'wait forever'.
#  flowable.idm.ldap.security-authentication=simple # The value that is used for the 'java.naming.security.authentication' property used to connect to the LDAP system.
#  flowable.idm.ldap.server= # The server host on which the LDAP system can be reached. For example 'ldap://localhost'.
#  flowable.idm.ldap.user= # The user id that is used to connect to the LDAP system.
#  flowable.idm.ldap.user-base-dn= # The base 'distinguished name' (DN) from which the searches for users are started.
#
#  # Flowable Mail FlowableMailProperties
#  flowable.mail.server.default-from=flowable@localhost # The default from address that needs to be used when sending emails.
#  flowable.mail.server.force-to= # The force to address(es) that would be used when sending out emails. IMPORTANT: If this is set then all emails will be send to defined address(es) instead of the address configured in the MailActivity.
#  flowable.mail.server.host=localhost # The host of the mail server.
#  flowable.mail.server.password= # The password for the mail server authentication.
#  flowable.mail.server.port=1025 # The port of the mail server.
#  flowable.mail.server.use-ssl=false # Sets whether SSL/TLS encryption should be enabled for the SMTP transport upon connection (SMTPS/POPS).
#  flowable.mail.server.use-tls=false # Set or disable the STARTTLS encryption.
#  flowable.mail.server.username= # The username that needs to be used for the mail server authentication. If empty no authentication would be used.
#
#  # Actuator
#  management.endpoint.flowable.cache.time-to-live=0ms # Maximum time that a response can be cached.
#  management.endpoint.flowable.enabled=true # Whether to enable the flowable endpoint.